name: publish
on: push

jobs:
  publish_docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            REPO_NAME=${{ github.event.repository.full_name }}
          tags: |
            ghcr.io/${{ github.event.repository.full_name }}:latest
            ghcr.io/${{ github.event.repository.full_name }}:${{ github.event.release.tag_name }}

      - name: Publish Docker image
        run: |
          docker push --all-tags ghcr.io/${{ github.event.repository.full_name }}
