name: publish
on: push

jobs:
  publish_docker:
    name: Build and push Docker image
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/${{ github.event.repository.full_name }}:latest
            # ghcr.io/${{ github.event.repository.full_name }}:${{ github.event.release.tag_name }}
      - name: Check Docker image
        run:
          docker run --rm -i -v ${PWD}:/docs ${{ github.event.repository.full_name }} build

      - name: Publish Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker push --all-tags ghcr.io/${{ github.event.repository.full_name }}
